modLoader="javafml"
loaderVersion="[25,)"
[[mods]]
    modId="testmod"
    displayName="Test Mod"
    version="0.0.1"
    authors="dags"
    description="A test mod"
[[dependencies.terraforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"