modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="testmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Reforged Test Mod" #mandatory
description="ConquestReforged test mod"